[package]
name = "burn_issues"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", features = ["wgpu", "train"], rev = "e2fa935" }
burn-ndarray = { git = "https://github.com/tracel-ai/burn", rev = "e2fa935" }
